// Mock Initial Dataset for StockSense UI and interactive flows

export const INITIAL_WAREHOUSES = [
  { id: 'wh-1', name: 'Main Distribution Hub', code: 'WH-MAIN', location: 'Section A - Bay 4' },
  { id: 'wh-2', name: 'West Coast Annex', code: 'WH-WEST', location: 'Building B' },
  { id: 'wh-3', name: 'Transit Cold Storage', code: 'WH-COLD', location: 'Facility 3' },
];

export const INITIAL_PRODUCTS = [
  {
    id: 'prod-1',
    sku: 'STL-ROD-01',
    name: 'Steel Rods (12mm)',
    category: 'Raw Materials',
    uom: 'Units',
    cost: 45.0,
    onHand: 140,
    freeToUse: 120,
    minStock: 50,
  },
  {
    id: 'prod-2',
    sku: 'ALU-SHT-04',
    name: 'Aluminum Sheets 4x8',
    category: 'Raw Materials',
    uom: 'Sheets',
    cost: 85.5,
    onHand: 18,
    freeToUse: 10,
    minStock: 25,
  },
  {
    id: 'prod-3',
    sku: 'HD-CHR-BLK',
    name: 'Ergonomic Desk Chair',
    category: 'Finished Goods',
    uom: 'Pieces',
    cost: 130.0,
    onHand: 42,
    freeToUse: 32,
    minStock: 15,
  },
  {
    id: 'prod-4',
    sku: 'BLT-HEX-M8',
    name: 'Hex Bolt M8x40',
    category: 'Hardware',
    uom: 'Boxes',
    cost: 12.0,
    onHand: 8,
    freeToUse: 4,
    minStock: 20,
  },
  {
    id: 'prod-5',
    sku: 'PKG-BOX-MED',
    name: 'Corrugated Box (Medium)',
    category: 'Packaging',
    uom: 'Bundles',
    cost: 18.0,
    onHand: 350,
    freeToUse: 310,
    minStock: 100,
  },
  {
    id: 'prod-6',
    sku: 'HYD-OIL-5L',
    name: 'Hydraulic Fluid 5L',
    category: 'Maintenance',
    uom: 'Cans',
    cost: 65.0,
    onHand: 5,
    freeToUse: 2,
    minStock: 12,
  },
];

export const INITIAL_RECEIPTS = [
  {
    id: 'rec-101',
    reference: 'IN/2026/00142',
    from: 'Apex Steel Industries',
    to: 'WH/Stock',
    contact: 'Markus Chen',
    scheduledDate: '2026-09-27',
    status: 'Ready',
    itemsCount: 3,
    totalQty: 150,
    warehouse: 'WH-MAIN',
  },
  {
    id: 'rec-102',
    reference: 'IN/2026/00143',
    from: 'Nordic Metalworks Ltd',
    to: 'WH/Input',
    contact: 'Sarah Lindqvist',
    scheduledDate: '2026-09-24', // late
    status: 'Waiting',
    itemsCount: 2,
    totalQty: 80,
    warehouse: 'WH-WEST',
    isLate: true,
  },
  {
    id: 'rec-103',
    reference: 'IN/2026/00144',
    from: 'Global Box Co.',
    to: 'WH/Stock',
    contact: 'David Miller',
    scheduledDate: '2026-09-28',
    status: 'Draft',
    itemsCount: 1,
    totalQty: 200,
    warehouse: 'WH-MAIN',
  },
  {
    id: 'rec-104',
    reference: 'IN/2026/00140',
    from: 'Vanguard Industrial Supplies',
    to: 'WH/Stock',
    contact: 'Elena Rostova',
    scheduledDate: '2026-09-22',
    status: 'Done',
    itemsCount: 4,
    totalQty: 320,
    warehouse: 'WH-MAIN',
  },
];

export const INITIAL_DELIVERIES = [
  {
    id: 'del-201',
    reference: 'OUT/2026/00088',
    from: 'WH/Stock',
    to: 'Acro Corp HQ',
    contact: 'James Vance',
    scheduledDate: '2026-09-27',
    status: 'Ready',
    itemsCount: 2,
    totalQty: 10,
    warehouse: 'WH-MAIN',
  },
  {
    id: 'del-202',
    reference: 'OUT/2026/00089',
    from: 'WH/Stock',
    to: 'Vertex Logistics',
    contact: 'Priya Sharma',
    scheduledDate: '2026-09-25', // late
    status: 'Waiting',
    itemsCount: 3,
    totalQty: 45,
    warehouse: 'WH-WEST',
    isLate: true,
  },
  {
    id: 'del-203',
    reference: 'OUT/2026/00090',
    from: 'WH/Stock',
    to: 'BuildCraft Interiors',
    contact: 'Robert Taylor',
    scheduledDate: '2026-09-29',
    status: 'Draft',
    itemsCount: 1,
    totalQty: 15,
    warehouse: 'WH-MAIN',
  },
  {
    id: 'del-204',
    reference: 'OUT/2026/00085',
    from: 'WH/Stock',
    to: 'Nexus Tech Systems',
    contact: 'Karen Scott',
    scheduledDate: '2026-09-20',
    status: 'Done',
    itemsCount: 2,
    totalQty: 25,
    warehouse: 'WH-COLD',
  },
];

export const INITIAL_ACTIVITIES = [
  {
    id: 'act-1',
    type: 'IN',
    reference: 'IN/2026/00140',
    product: 'Steel Rods (12mm)',
    qty: '+50 Units',
    location: 'WH/Stock',
    contact: 'Vanguard Industrial Supplies',
    time: '12 mins ago',
    status: 'Done',
  },
  {
    id: 'act-2',
    type: 'OUT',
    reference: 'OUT/2026/00085',
    product: 'Ergonomic Desk Chair',
    qty: '-10 Pieces',
    location: 'Acro Corp HQ',
    contact: 'Nexus Tech Systems',
    time: '45 mins ago',
    status: 'Done',
  },
  {
    id: 'act-3',
    type: 'IN',
    reference: 'IN/2026/00142',
    product: 'Corrugated Box (Medium)',
    qty: '+100 Bundles',
    location: 'WH/Stock',
    contact: 'Apex Steel Industries',
    time: '2 hours ago',
    status: 'Ready',
  },
  {
    id: 'act-4',
    type: 'OUT',
    reference: 'OUT/2026/00088',
    product: 'Hex Bolt M8x40',
    qty: '-6 Boxes',
    location: 'Customer Bay 2',
    contact: 'James Vance',
    time: '4 hours ago',
    status: 'Ready',
  },
  {
    id: 'act-5',
    type: 'ADJUST',
    reference: 'ADJ/2026/00012',
    product: 'Hydraulic Fluid 5L',
    qty: '-2 Cans (Count Delta)',
    location: 'WH/Stock',
    contact: 'Internal Adjustment',
    time: '1 day ago',
    status: 'Done',
  },
];
